### ISSUE TITLE
rename chapter 11 title "futures"

### ISSUE THREAD

**Issue by dengdenglele** [digital-work-lab/digital-work-lecture#6]
Futures is a term typically used in finance for "Termingeschäfte".

https://en.wikipedia.org/wiki/Futures_contract

Proposition to rename chapter to "future prospects" to make the term less ambigious.

**Comment by geritwagner** [comment]
Thank you for raising this question. I have added a footnote to explain the meaning of the term "futures" in our context: c0137c7c540b34893aa31b374a31818d1601f04b.
